### ISSUE TITLE
nm_write deprecation warning

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/mrgda#114]
`nm_write` is listed as deprecated, but the documentation does not state what function should be used instead.

https://github.com/metrumresearchgroup/mrgda/blob/9c6a4a4ae5166effe7ee81c43741dd84640701f8/R/nm-write.R#L2

**Comment by andersone1** [comment]
Good catch @callistosp , tagging @michaelmcd18 to ensure he's aware as well.

Just FYI, the replacement is `write_derived`
