### ISSUE TITLE
ambiguous warning

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/mrgda#163]
If we are missing RATE/DUR from the data set, we get the following warning that a test was omitted:
`! Some tests skipped due to missing flags: amt, dur, rate`

This is misleading to the user because it makes it seem like there is no AMT column. I would suggest that we just list `dur, rate` as the missing flags for this warning.

**Comment by michaelmcd18** [comment]
Hey @callistosp, I believe the warning message you're talking about was coming from `nm_validate()`. We actually removed this function from the package as we found using: `NMdata::NMcheckData(data = pk_out, col.row = "NUM")` to be more useful. I recommend using this the same way you were using `nm_validate()`
