### ISSUE TITLE
uninformative error message

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/mrgda#185]
After calling the function `mrgda::write_derived`I get the following warning message:

```
Warning message:
One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat) 
```

Since `vroom` is being used under the hood, I can't figure out why the warning is being raised, and when I try calling `problems` on my input data set, I get no output.

**Comment by andersone1** [comment]
@callistosp what version of `mrgda` are you using?

**Comment by michaelmcd18** [comment]
@andersone1 `mrgda 0.10.0`

**Comment by andersone1** [comment]
@callistosp @michaelmcd18 

Typically those are caused by using `readr::read_csv(...)` when `data.table::fread(...)` would be the better option (with all options in the function set to the same as they were to write the data, e.g. `quote=FALSE`, etc).

**Comment by michaelmcd18** [comment]
@andersone1  The warning message is being generated when the `history.csv` is being created.

**Comment by michaelmcd18** [comment]
Maybe from this line
```
.cur_history <- tryCatch(
    suppressMessages(readr::read_csv(file.path(.meta_data_folder, "history.csv"))),
    error = identity
  )
  ```

**Comment by andersone1** [comment]
Yep, @michaelmcd18 . I bet that is it.

**Comment by callistosp** [comment]
nice work, thanks both!
