### ISSUE TITLE
Unchanged rows being flagged by execute_data_diffs

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/mrgda#207]
I have encountered an error where an unchanged dataset gets flagged for being changed, but the `subject-diffs.csv` just looks like this:
```
ID,VARIABLE,BASE,COMPARE,N Occurrences
1,C,.,.,157
10,C,.,.,47
101,C,.,.,89
```

The C column has not changed, but it is being flagged as changed for all subjects/obs. I ran `diffdf::diffdf` on the underlying data and it does not flag these rows as being changed.

Also, it would be nice if `subject-diffs.csv` were sorted numerically by ID rather than alphabetically by ID.

**Comment by andersone1** [comment]
Thank you for letting us know @callistosp .

Would it be possible to point us to the repo/scripts so we can try to recreate it on our end?

**Comment by michaelmcd18** [comment]
@andersone1 I can recreate it here:
```
df1 <- system.file("derived/pk.csv", package = "mrgda")
spec <- yspec::ys_load(system.file("derived/pk.yml", package = "mrgda"))

df2 <-
  data.table::fread(
  file = df1,
  sep = ",",
  quote = FALSE,
  na = "."
) %>% as.data.frame

write_derived(df2, .spec = spec, .file = here::here("inst/derived/pk.csv"))
```
<img width="596" alt="Screenshot 2024-04-16 at 8 34 11 AM" src="https://github.com/metrumresearchgroup/mrgda/assets/104217788/cfb4ef58-e6bf-40df-9641-35e0a7579a8e">

**Comment by michaelmcd18** [comment]
Getting the same result when the `ADAT` column has NAs or is set to "." before writing out the data. Seems like this only happens when the column has both empty rows and non-NA characters
