### ISSUE TITLE
Review Comments (running list - will continue to add as I go)

### ISSUE THREAD

**Issue by curtisKJ** [metrumresearchgroup/mrgda#27]
- Should we make a commentary regarding the output of `nm_summary`, specifically that we should not use that for EDA?
- Can you request that the Study contrast isn't used? It may get too busy if there are 10 studies in a dataset for the figures.
- For the tables, the grouping by Study makes sense, but could we add an "overall" summary at the bottom line for both continuous and categorical?
- Suggest adding BLQ values descriptions into the yaml, and adding the BLQ summary as an output for the tables? This is something I'd want a quick look at - how many BLQs do I have. 
- The summary function outputs the plots twice, once based on the print statement, and the other time on the return statement. Perhaps, making `return` conditional on the .figure_prompt variable would be better. So if .figure_prompt = T, then we don't return the figures, but if .figure_prompt = F we do. 
- Can we put in more detail regarding what level of granularity gets output in the PDF in function help? Perhaps just a brief statement regarding the link to the spec file. 
- For time-varying covariates, a quick spaghetti plot (TV-cov vs. Time) grouped by ID could be useful to see that nothing "weird" is going on. 
- Can we add alternative GFR calculation equations? 
- Could we add pediatric GFR equations, too? At the very least maybe a warning for the standard function if it detects ages below 20 years old?

**Comment by michaelmcd18** [comment]
Adding an extra argument `.study_compare`. If set to TRUE the tables and figures will be grouped by study. You can set to FALSE to see tables and figures without any grouping (full data summaries). This should address the two bullet points below

- Can you request that the Study contrast isn't used? It may get too busy if there are 10 studies in a dataset for the figures.
- For the tables, the grouping by Study makes sense, but could we add an "overall" summary at the bottom line for both continuous and categorical?

**Comment by michaelmcd18** [comment]
- Suggest adding BLQ values descriptions into the yaml, and adding the BLQ summary as an output for the tables? This is something I'd want a quick look at - how many BLQs do I have.

Added new BLQ table

**Comment by michaelmcd18** [comment]
- The summary function outputs the plots twice, once based on the print statement, and the other time on the return statement. Perhaps, making return conditional on the .figure_prompt variable would be better. So if .figure_prompt = T, then we don't return the figures, but if .figure_prompt = F we do.

Fixed with updated format

**Comment by michaelmcd18** [comment]
Added spaghetti plots to `nm_summary` for all time varying covariates
