### ISSUE TITLE
changing data-diff functionality

### ISSUE THREAD

**Issue by callistosp** [metrumresearchgroup/mrgda#61]
As a user, I would like the `nm_write` function to warn me if there was a difference in the data set. Silently generating a `data-diff.txt` file requires me to check this file every time I rerun the script even if no change resulted. 

Related thought: currently the file is just overwritten entirely, so you lose the history of the changes if any occurred. Would it make sense to append to the file rather than overwrite it completely?

**Comment by michaelmcd18** [comment]
@callistosp We can have a message come up saying no difference was found in the string of messages `nm_write` outputs while it's writing out data to the folder. 

For the diff, would using svn's history work or would you prefer a continuous text file that's updated each time the data is written out?

**Comment by callistosp** [comment]
@michaelmcd18 yeah I think just sending a message to the user that summarizes the differences would be nice, even if there is none.

I think you're right that to some degree you could leverage version control to track the changes over time. The more I think about it the less useful I think it would be to have an ever-growing list of changes to the data set.

**Comment by michaelmcd18** [comment]
@callistosp Definitely agreed, we'll have a message if there's no differences and stick with overwriting that file for now and rely on svn for any version history.

Thanks for the input on this Sam!
