### ISSUE TITLE
Light wrapper function around nmcheckdata with common metrum defaults

### ISSUE THREAD

**Issue by andersone1** [metrumresearchgroup/mrgda#95]

**Comment by michaelmcd18** [comment]
Will deprecate `nm_validate()` and create `validate_nm()` as the wrapper around NMCheckData

**Comment by andersone1** [comment]
`NMcheckData` returns an object that may be worthing looking into as well (this could also be for future versions).

```
x <- NMdata::NMcheckData(nm, col.row = "NUM")
View(x)
```
